#pragma once
#include "keira/app.h"
#include <vector>

// Manifest generated by firmware workflow (tools/gen_firmware_json.py)
#define KEIRA_UPDATE_MANIFEST_URL "https://github.com/lilka-dev/keira/releases/latest/download/keira_firmware.json"

#define KEIRA_UPDATE_HTTP_TIMEOUT 15000
#define KEIRA_UPDATE_RX_BUFFER    4096
// GitHub redirects release downloads to long signed URLs
#define KEIRA_UPDATE_TX_BUFFER    2048
#define KEIRA_UPDATE_MANIFEST_MAX (64 * 1024)

// Updates Keira itself over the air using firmware published in GitHub releases
class KeiraUpdateApp : public App {
public:
    KeiraUpdateApp();

private:
    struct FirmwareVersion {
        String version;
        String tag;
        bool prerelease = false;
        String date;
        String url;
        String language;
        uint32_t size = 0;
    };

    void run() override;
    bool fetchManifest(String& out);
    bool parseManifest(const String& json);
    void install(const FirmwareVersion& fw);

    static String currentLanguage();
    static String currentVersion();

    std::vector<FirmwareVersion> versions;
};
