# Lilka v2: ESP32-S3, 16 MB QIO flash, 8 MB octal PSRAM

set(IDF_TARGET "esp32s3" CACHE STRING "IDF Build Target")

# arduino-esp32 2.0.17 supports ESP-IDF 4.4.x only
set(KEIRA_IDF_VERSION "4.4.7")

set(KEIRA_BOARD_DEFINITIONS
    ARDUINO_LILKA
    LILKA_VERSION=2
    ARDUINO_USB_MODE=1
    ARDUINO_USB_CDC_ON_BOOT=1
    ARDUINO_RUNNING_CORE=1
    ARDUINO_EVENT_RUNNING_CORE=1
    BOARD_HAS_PSRAM
    F_CPU=240000000L
)
